// 这在 Node.js 中运行 - 不要在这里使用客户端代码（浏览器 API、JSX...）
/**
 * 启用 TypeScript 级别的静态类型检查和编辑器提示（即便这是 JS 文件）。
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
//sidebars是导出的主对象
const sidebars = {
  //里面的每一个都是独立的侧边栏id
  //type:autogenerated(自动创建)，category(手动定义)
  tutorialSidebar: [{type: 'autogenerated', dirName: 'knowledgeBase'}],
  technicalsupport: [{type: 'autogenerated', dirName: 'technicalsupport'}],
  softwareInstall: [{type: 'autogenerated', dirName: 'softwareInstall'}],
  update: [{type: 'autogenerated', dirName: 'update'}],
  userGuide: [{type: 'autogenerated', dirName: 'userGuide'}],

  // 但是你可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
